# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"fixture-site@workspace:.":
  version: 0.0.0-use.local
  resolution: "fixture-site@workspace:."
  dependencies:
    sass: "npm:^1.93.2"
    vite: "npm:^8.0.10"
  languageName: unknown
  linkType: soft

"sass@npm:^1.93.2":
  version: 1.93.2
  resolution: "sass@npm:1.93.2"
  languageName: node
  linkType: hard

"vite@npm:^8.0.10":
  version: 8.0.10
  resolution: "vite@npm:8.0.10"
  languageName: node
  linkType: hard
