# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


sass@^1.93.2:
  version "1.93.2"
  resolved "https://registry.yarnpkg.com/sass/-/sass-1.93.2.tgz"

vite@^8.0.10:
  version "8.0.10"
  resolved "https://registry.yarnpkg.com/vite/-/vite-8.0.10.tgz"
